"""Notification model — stores user-facing notifications for the bell icon system."""

from datetime import datetime

from sqlalchemy import JSON, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class Notification(Base):
    """User notification for the bell icon dropdown.

    Notifications are generated by multiple sources:
    - AI agent decisions (buy/sell signals, portfolio match results)
    - Risk engine (stop-loss hit, take-profit hit, trailing stop updates)
    - Trade executor (order filled, order rejected)
    - Intelligence platform (new opportunities, consensus changes, high-impact news)
    - System (scheduler started/stopped, errors)
    """

    __tablename__ = "notifications"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(nullable=False, default=0, index=True)
    # trade_executed, signal_alert, stop_loss_hit, take_profit_hit,
    # trailing_stop_update, news_high_impact, risk_warning, ai_decision,
    # portfolio_change, system_event, consensus_change
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # info, warning, critical
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")
    asset: Mapped[str | None] = mapped_column(String(20), nullable=True)
    # Optional URL or page to navigate to when clicked
    action_url: Mapped[str | None] = mapped_column(String(200), nullable=True)
    # JSON metadata for extra context (e.g. {"symbol": "BTCUSDT", "price": 45000})
    metadata_json: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    read_at: Mapped[datetime | None] = mapped_column(nullable=True, default=None)
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, default=func.now(), server_default=func.now()
    )

    __table_args__ = (
        Index("ix_notif_user_read", "user_id", "read_at"),
        Index("ix_notif_user_created", "user_id", "created_at"),
        Index("ix_notif_type", "type"),
    )
