"""initial

Revision ID: f9b6da5b0e6e
Revises: 
Create Date: 2026-07-22 23:57:42.349695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b6da5b0e6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('total_return_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualized_return_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('avg_position_duration', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_exposure', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_runs_end_date', 'backtest_runs', ['end_date'], unique=False)
    op.create_index('ix_backtest_runs_start_date', 'backtest_runs', ['start_date'], unique=False)
    op.create_index('ix_backtest_runs_strategy_name', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_table('market_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_bars_symbol', 'market_bars', ['symbol'], unique=False)
    op.create_index('ix_market_bars_symbol_timeframe', 'market_bars', ['symbol', 'timeframe'], unique=False)
    op.create_index('ix_market_bars_timestamp', 'market_bars', ['timestamp'], unique=False)
    op.create_index('ix_market_bars_unique', 'market_bars', ['timestamp', 'symbol', 'timeframe'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_versions_name', 'model_versions', ['name'], unique=False)
    op.create_index('ix_model_versions_name_version', 'model_versions', ['name', 'version'], unique=True)
    op.create_index('ix_model_versions_status', 'model_versions', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_opened_at', 'positions', ['opened_at'], unique=False)
    op.create_index('ix_positions_status', 'positions', ['status'], unique=False)
    op.create_index('ix_positions_strategy', 'positions', ['strategy_name'], unique=False)
    op.create_index('ix_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('suggested_stop_loss', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('suggested_take_profit', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_status', 'signals', ['status'], unique=False)
    op.create_index('ix_signals_strategy', 'signals', ['strategy_name'], unique=False)
    op.create_index('ix_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_timestamp', 'signals', ['timestamp'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_runs_mode', 'strategy_runs', ['mode'], unique=False)
    op.create_index('ix_strategy_runs_status', 'strategy_runs', ['status'], unique=False)
    op.create_index('ix_strategy_runs_strategy_name', 'strategy_runs', ['strategy_name'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_events_level', 'system_events', ['level'], unique=False)
    op.create_index('ix_system_events_source', 'system_events', ['source'], unique=False)
    op.create_index('ix_system_events_timestamp', 'system_events', ['timestamp'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('equity', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_snapshots_strategy_run_id', 'account_snapshots', ['strategy_run_id'], unique=False)
    op.create_index('ix_account_snapshots_timestamp', 'account_snapshots', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_signal_id'), 'orders', ['signal_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_symbol', 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_timestamp', 'orders', ['timestamp'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_event_type', 'risk_events', ['event_type'], unique=False)
    op.create_index('ix_risk_events_severity', 'risk_events', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_events_signal_id'), 'risk_events', ['signal_id'], unique=False)
    op.create_index('ix_risk_events_timestamp', 'risk_events', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_position_id'), 'trades', ['position_id'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_timestamp', 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_timestamp', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index(op.f('ix_trades_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_risk_events_timestamp', table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_signal_id'), table_name='risk_events')
    op.drop_index('ix_risk_events_severity', table_name='risk_events')
    op.drop_index('ix_risk_events_event_type', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_orders_timestamp', table_name='orders')
    op.drop_index('ix_orders_symbol', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_signal_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_account_snapshots_timestamp', table_name='account_snapshots')
    op.drop_index('ix_account_snapshots_strategy_run_id', table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index('ix_system_events_timestamp', table_name='system_events')
    op.drop_index('ix_system_events_source', table_name='system_events')
    op.drop_index('ix_system_events_level', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_strategy_runs_strategy_name', table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_status', table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_mode', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index('ix_signals_timestamp', table_name='signals')
    op.drop_index('ix_signals_symbol', table_name='signals')
    op.drop_index('ix_signals_strategy', table_name='signals')
    op.drop_index('ix_signals_status', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_index('ix_positions_strategy', table_name='positions')
    op.drop_index('ix_positions_status', table_name='positions')
    op.drop_index('ix_positions_opened_at', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_model_versions_status', table_name='model_versions')
    op.drop_index('ix_model_versions_name_version', table_name='model_versions')
    op.drop_index('ix_model_versions_name', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_market_bars_unique', table_name='market_bars')
    op.drop_index('ix_market_bars_timestamp', table_name='market_bars')
    op.drop_index('ix_market_bars_symbol_timeframe', table_name='market_bars')
    op.drop_index('ix_market_bars_symbol', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_index('ix_backtest_runs_strategy_name', table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_start_date', table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_end_date', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
