import type {
  SupportedBroker,
  BrokerAccount,
  BrokerCapabilityFlags,
  MarketType,
  BrokerEnvironment,
} from "./brokerTypes";

export const MOCK_SUPPORTED_BROKERS: SupportedBroker[] = [
  {
    brokerId: "binance",
    displayName: "Binance",
    logoUrl: null,
    websiteUrl: "https://www.binance.com",
    apiDocsUrl: "https://binance-docs.github.io/apidocs",
    supportedMarkets: ["spot" as MarketType],
    capabilities: {
      spot: true,
      margin: false,
      futures: false,
      staking: false,
      earn: true,
      websocket: true,
      marketOrders: true,
      limitOrders: true,
      stopOrders: true,
      withdrawals: false,
    } as BrokerCapabilityFlags,
    requiresPassphrase: false,
    environments: ["testnet", "live"] as BrokerEnvironment[],
    implemented: true,
  },
  {
    brokerId: "bybit",
    displayName: "Bybit",
    logoUrl: null,
    websiteUrl: "https://www.bybit.com",
    apiDocsUrl: "https://bybit-exchange.github.io/docs/v5/intro",
    supportedMarkets: ["spot", "futures"] as MarketType[],
    capabilities: {
      spot: true,
      margin: true,
      futures: true,
      staking: false,
      earn: false,
      websocket: true,
      marketOrders: true,
      limitOrders: true,
      stopOrders: true,
      withdrawals: false,
    } as BrokerCapabilityFlags,
    requiresPassphrase: false,
    environments: ["testnet", "live"] as BrokerEnvironment[],
    implemented: false,
  },
  {
    brokerId: "coinbase",
    displayName: "Coinbase",
    logoUrl: null,
    websiteUrl: "https://www.coinbase.com",
    apiDocsUrl: "https://docs.cloud.coinbase.com",
    supportedMarkets: ["spot", "futures"] as MarketType[],
    capabilities: {
      spot: true,
      margin: false,
      futures: true,
      staking: true,
      earn: true,
      websocket: true,
      marketOrders: true,
      limitOrders: true,
      stopOrders: false,
      withdrawals: false,
    } as BrokerCapabilityFlags,
    requiresPassphrase: false,
    environments: ["sandbox", "live"] as BrokerEnvironment[],
    implemented: false,
  },
  {
    brokerId: "kraken",
    displayName: "Kraken",
    logoUrl: null,
    websiteUrl: "https://www.kraken.com",
    apiDocsUrl: "https://docs.kraken.com",
    supportedMarkets: ["spot", "margin"] as MarketType[],
    capabilities: {
      spot: true,
      margin: true,
      futures: false,
      staking: true,
      earn: false,
      websocket: true,
      marketOrders: true,
      limitOrders: true,
      stopOrders: true,
      withdrawals: false,
    } as BrokerCapabilityFlags,
    requiresPassphrase: false,
    environments: ["live"] as BrokerEnvironment[],
    implemented: false,
  },
  {
    brokerId: "okx",
    displayName: "OKX",
    logoUrl: null,
    websiteUrl: "https://www.okx.com",
    apiDocsUrl: "https://www.okx.com/docs-v5",
    supportedMarkets: ["spot", "margin", "futures"] as MarketType[],
    capabilities: {
      spot: true,
      margin: true,
      futures: true,
      staking: true,
      earn: true,
      websocket: true,
      marketOrders: true,
      limitOrders: true,
      stopOrders: true,
      withdrawals: false,
    } as BrokerCapabilityFlags,
    requiresPassphrase: true,
    environments: ["demo", "live"] as BrokerEnvironment[],
    implemented: false,
  },
];

export const MOCK_CONNECTED_ACCOUNTS: BrokerAccount[] = [];
